[package]
name = "lux"
version = "0.1.0"
edition = "2021"

[dependencies]
lux_lib = { path = "crates/lux_lib" }

[workspace]
members = ["crates/*"]

[workspace.dependencies]
bevy = { version = "0.12", default-features = false }
bevy_sync = "0.12.9"
bevy_oxr = "0.1.0"

[features]
default = []
xr = ["lux_lib/xr"]
