[package]
name = "lux"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12" }
bevy_sync = "0.12.1"
bevy_oxr = "0.1.0"
clap = { version = "4.3.0", features = ["derive"] }
serde = { version = "1.0.160", features = ["derive"] }
lux_cli = { path = "crates/lux_cli" }
lux_components = { path = "crates/lux_components" }
lux_desktop = { path = "crates/lux_desktop" }
lux_desktop_camera = { path = "crates/lux_desktop_camera" }

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[workspace]
members = ["crates/*"]
