[package]
name = "lux"
version = "0.1.0"
edition = "2021"

[dependencies]
lux_lib = { path = "crates/lux_lib" }

[workspace]
members = ["crates/*"]

[workspace.dependencies]
bevy_sync = "0.12.7" # { path = "../bevy_sync" }

[features]
default = []
xr = ["lux_lib/xr"]
