[package]
name = "lux_avatar_vrm"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
avian3d.workspace = true
bevy_vr_controller.workspace = true

[features]
default = []
xr = []
