[package]
name = "lux_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12", default-features = false }
bevy_sync = "0.12.5"
lux_cli = { path = "../lux_cli" }

[dev-dependencies]
bevy_editor_pls = "0.6"
