name: Build
on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "docs/*"
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Cache"
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "linux-"
      - name: "External dependencies"
        run: sudo apt-get install -y libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev libudev-dev
      - name: "Checks"
        run: |
          cargo fmt --check
          cargo clippy --no-deps --tests -- -D warnings
      - name: "Test"
        run: |
          cargo test
      - name: "Build"
        run: |
          cargo build --release
      - name: "Upload"    
        uses: actions/upload-artifact@v3
        with:
          name: linux-lux
          path: target/release/lux
  windows:
    runs-on: windows-latest
    steps:
      - name: disable git eol translation
        run: git config --global core.autocrlf false
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Cache"
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "windows-"
      - name: Install Rustup using win.rustup.rs
        shell: powershell
        run: |
          # Disable the download progress bar which can cause perf issues
          $ProgressPreference = "SilentlyContinue"
          Invoke-WebRequest https://win.rustup.rs/ -OutFile rustup-init.exe
          .\rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --default-toolchain=none
          del rustup-init.exe
          rustup target add x86_64-pc-windows-msvc
      - name: "Checks"
        shell: cmd
        run: |
          cargo fmt --check || exit /b 1
          cargo clippy --no-deps --tests -- -D warnings || exit /b 1
      - name: "Test"
        shell: cmd
        run: |
          cargo test || exit /b 1
      - name: "Build"
        shell: cmd
        run: |
          cargo build --release || exit /b 1
      - name: "Upload"    
        uses: actions/upload-artifact@v3
        with:
          name: windows-lux
          path: target/release/lux.exe
  mac:
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Cache"
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "max-"
      - name: "Checks"
        run: |
          cargo fmt --check
          cargo clippy --no-deps --tests -- -D warnings
      - name: "Test"
        run: |
          cargo test
      - name: "Build"
        run: |
          cargo build --release
      - name: "Upload"    
        uses: actions/upload-artifact@v3
        with:
          name: mac-lux
          path: target/release/lux

